services:
  mysql:
    image: mysql:8.0
    container_name: mysql-oots
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: oots_db
      MYSQL_USER: oots_user
      MYSQL_PASSWORD: oots_password
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
